framework:
  rate_limiter:
    admin_invite:
      policy: fixed_window
      limit: 20
      interval: '1 hour'
    invite_activation:
      policy: fixed_window
      limit: 15
      interval: '1 hour'
    password_reset_request:
      policy: fixed_window
      limit: 10
      interval: '1 hour'
    password_reset_complete:
      policy: fixed_window
      limit: 15
      interval: '1 hour'
